ugpapa/dev_learning

nguyen/24Feb_Chapter1_Lesson11.html, nguyen/24Feb_Chapter1_Lesson12.html, nguyen/index.html, nguyen/readme.md, nguyen/util/README.md
Link: https://threejs-journey.com/lessons/materials#
=> feat: update GUI Test for lesson 12

nguyen/24Feb_Chapter1_Lesson11.html, nguyen/24Feb_Chapter1_Lesson12.html, nguyen/24Feb_Chapter1_Lesson13.html, nguyen/27Feb_Chapter2_Lesson15.html, nguyen/27Feb_Chapter2_Lesson16.html, nguyen/index.html
Link: https://threejs-journey.com/lessons/shadows
=> Mysterio chapter2

nguyen/27Feb_Chapter2_Lesson16.html
Link: https://threejs-journey.com/lessons/lights
Link: https://threejs-journey.com/lessons/shadows
=> Mysterio chap2

nguyen/28Feb_Chapter2_Lesson19.html
Link: https://threejs-journey.com/lessons/galaxy-generator#
=> feat: add lesson 19 chapter 2

nguyen/01Mar_Chapter2_Lesson20.html
Link: https://threejs-journey.com/lessons/scroll-based-animation#
=> feat: add lesson 20 chapter 2

nguyen/28Feb_Chapter2_Lesson18.html, nguyen/28Feb_Chapter2_Lesson19.html
=> fix: fix gui bug

nguyen/07Mar_Chapter3_Lesson25.html
Link: https://threejs-journey.com/lessons/realistic-render#
=> feat: add lesson 25 chapter 3

nguyen/09Mar_Chapter3_Lesson28.html, nguyen/shaders/waterfragment.glsl, nguyen/shaders/watervertex.glsl
Link: https://threejs-journey.com/lessons/raging-sea
=> feat: add lesson 29 chap 3

pauline/09-March/Experience/Utils/Resources.js, pauline/09-March/script.js
Link: https://threejs-journey.com/lessons/xx
=> feat: todo

nguyen/projectLivingRoom/10Mar_LivingRoom.html
=> feat: add reset camera view, support keyboard movement

nguyen/projectLivingRoom/14Mar_LivingRoom_FirstPerson.html
=> feat: add first person perspective

nguyen/projectLivingRoom/10Mar_LivingRoom.html
=> feat: update vanilla room camera restriction

nguyen/projectLivingRoom/10Mar_LivingRoom.html, nguyen/projectSolarSystem/13Mar_SolarSystem_Enhance.html
=> fix: fix camera pos when change default camera

nguyen/projectSolarSystem/13Mar_SolarSystem_Enhance.html
=> feat: update description for planet system

nguyen/projectLivingRoom/10Mar_LivingRoom.html, nguyen/projectLivingRoom/14Mar_LivingRoom_FirstPerson.html, nguyen/projectSolarSystem/13Mar_SolarSystem_Enhance.html
=> feat: enhance assignment 2

nguyen/projectLivingRoom/10Mar_LivingRoom.html, nguyen/projectLivingRoom/14Mar_LivingRoom_FirstPerson.html
=> chore: refactor & remove unnecessary code

nguyen/projectGalaxy/Mar20_GalaxySpiral.html, nguyen/projectGalaxy/Mar20_GalaxyTestFileNotUse.html
=> feat: update camera animation

nguyen/22Mar_Chapter5_Lesson32.html, nguyen/24Feb_Chapter1_Lesson11.html
Link: https://threejs-journey.com/lessons/post-processing
=> feat: add lesson 32 chapter 5

nguyen/22Mar_Chapter5_Lesson32.html
Link: https://threejs-journey.com/lessons/performance-tips
=> feat: add FPS meter from lesson 33

pauline/09-March/Experience/Camera.js, pauline/09-March/Experience/Experience.js, pauline/09-March/Experience/World/Item.js, pauline/09-March/Experience/World/World.js, pauline/diagonalCircle/Experience/Utils/Resources.js, pauline/diagonalCircle/Experience/World/Environment.js, pauline/diagonalCircle/Experience/World/Particles.js, pauline/diagonalCircle/script.js
Link: https://threejs-journey.com/lessons/xx
=> fix: temporary manual camera

pauline/09-March/Experience/Camera.js, pauline/09-March/Experience/Experience.js, pauline/09-March/Experience/World/Item.js, pauline/09-March/Experience/World/Person.js, pauline/09-March/Experience/World/Room.js, pauline/09-March/Experience/World/World.js
Link: https://threejs-journey.com/lessons/xx
=> feat: automatic control
